// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_UVV_Fintech.Banco_Dados.Entities;

#nullable disable

namespace Projeto_UVV_Fintech.Migrations
{
    [DbContext(typeof(DB_Context))]
    partial class DB_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Projeto_UVV_Fintech.Banco_Dados.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAdesao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeContas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Projeto_UVV_Fintech.Banco_Dados.Entities.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<int>("NumeroConta")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Saldo")
                        .HasColumnType("REAL");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contas", (string)null);

                    b.HasDiscriminator<string>("TipoConta").HasValue("Conta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Projeto_UVV_Fintech.Banco_Dados.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaDestinatarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaRemetenteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ContaDestinatarioId");

                    b.HasIndex("ContaId");

                    b.HasIndex("ContaRemetenteId");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("Projeto_UVV_Fintech.Banco_Dados.Entities.ContaCorrente", b =>
                {
                    b.HasBaseType("Projeto_UVV_Fintech.Banco_Dados.Entities.Conta");

                    b.ToTable("Contas", (string)null);

                    b.HasDiscriminator().HasValue("Corrente");
                });

            modelBuilder.Entity("Projeto_UVV_Fintech.Banco_Dados.Entities.ContaPoupanca", b =>
                {
                    b.HasBaseType("Projeto_UVV_Fintech.Banco_Dados.Entities.Conta");

                    b.Property<int>("SaquesRealizadosNoMes")
                        .HasColumnType("INTEGER");

                    b.ToTable("Contas", (string)null);

                    b.HasDiscriminator().HasValue("Poupanca");
                });

            modelBuilder.Entity("Projeto_UVV_Fintech.Banco_Dados.Entities.Conta", b =>
                {
                    b.HasOne("Projeto_UVV_Fintech.Banco_Dados.Entities.Cliente", "Cliente")
                        .WithMany("Contas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Projeto_UVV_Fintech.Banco_Dados.Entities.Transacao", b =>
                {
                    b.HasOne("Projeto_UVV_Fintech.Banco_Dados.Entities.Conta", "ContaDestinatario")
                        .WithMany()
                        .HasForeignKey("ContaDestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Projeto_UVV_Fintech.Banco_Dados.Entities.Conta", null)
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaId");

                    b.HasOne("Projeto_UVV_Fintech.Banco_Dados.Entities.Conta", "ContaRemetente")
                        .WithMany()
                        .HasForeignKey("ContaRemetenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContaDestinatario");

                    b.Navigation("ContaRemetente");
                });

            modelBuilder.Entity("Projeto_UVV_Fintech.Banco_Dados.Entities.Cliente", b =>
                {
                    b.Navigation("Contas");
                });

            modelBuilder.Entity("Projeto_UVV_Fintech.Banco_Dados.Entities.Conta", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
